README.md
Some people might not realize they need to change folder to web-ui.
=> Updated README.md to add command for changing folder

src/app/app.component.ts, src/app/auth/auth.component.ts, src/app/core/_services/shared/config.service.ts
Fixes https://github.com/hashtopolis/server/issues/982
=> Setting backendurl even if config.json returns error

src/app/account/settings/acc-settings/acc-settings.component.html, src/app/account/settings/acc-settings/acc-settings.component.spec.ts, src/app/account/settings/acc-settings/acc-settings.component.ts, src/app/core/_validators/password.validator.ts, src/app/shared/grid-containers/grid-formgroup.ts
- Basic tests for the account settings form
- A new _validators dir in core including a validator for matching passwords
- Some minor refactoring to minimize duplicate code
=> Basic tests for account settings

.eslintrc.json, .prettierrc.json, package-lock.json, package.json
This PR includes
- Prettier code formatter: https://prettier.io/
- script to format code
Running `npm run format` will reformat all files to the configured format. That PR will be huge so those changes are not included.
=> Added prettier code formatter

.devcontainer/devcontainer.json, .eslintrc.json, .vscode/settings.json, package-lock.json, package.json, src/app/core/_components/tables/agents-table/agents-table.component.ts, src/app/core/_components/tables/agents-table/agents-table.constants.ts, src/app/core/_components/tables/ht-table/ht-table.component.html, src/app/core/_components/tables/ht-table/ht-table.models.ts, src/app/core/_datasources/agents.datasource.ts, src/app/core/_models/agent.model.ts, src/styles/components/_table.scss
- Fix broken routerLinks in agents-table
- Allow a cell to display a list of links
- Added prettier and sort-imports extensions to devcontainer conf
- Added linter settings to repo
=> Fix routerLinks in agents-table + allow multiple routerLinks per cell 

src/app/core/_services/files/files_tus.service.ts
The procedure for obtaining the token has been modified, and upon clicking, the bearer token is not present. In the request we add back the bearer token.
=> File tus service missing token

src/app/core/_components/core-components.module.ts, src/app/core/_components/menus/base-menu/base-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.constants.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.component.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.constants.ts, src/app/core/_components/tables/files-table/files-table.component.html, src/app/core/_components/tables/files-table/files-table.component.ts, src/app/core/_components/tables/files-table/files-table.constants.ts, src/app/core/_components/tables/ht-table/ht-table.component.html, src/app/core/_components/tables/ht-table/ht-table.models.ts, src/app/core/_datasources/files.datasource.ts, src/app/core/_models/access-group.model.ts, src/app/core/_models/config-ui.model.ts, src/app/core/_models/file.model.ts, src/app/files/files-edit/files-edit.component.html, src/app/files/files.component.html, src/app/files/files.component.ts, src/app/files/files.module.ts, src/app/layout/header/header.component.html, src/app/layout/header/header.component.ts, src/app/layout/header/header.model.ts, src/app/shared/utils/util.ts, src/styles/layout/_header.scss
- New files datasource
- New files-table component
- Change logo in dark mode
=> Files table

src/app/config/engine/crackers/crackers.component.html, src/app/core/_components/core-components.module.ts, src/app/core/_components/menus/base-menu/base-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.constants.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.component.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.constants.ts, src/app/core/_components/tables/crackers-table/crackers-table.component.html, src/app/core/_components/tables/crackers-table/crackers-table.component.ts, src/app/core/_components/tables/crackers-table/crackers-table.constants.ts, src/app/core/_components/tables/ht-table/ht-table.models.ts, src/app/core/_datasources/crackers.datasource.ts, src/app/core/_models/config-ui.model.ts, src/app/core/_models/cracker-binary.model.ts
- New crackers datasource
- New crackers table component
- Menu implementations
=> Crackers table

src/app/config/log/log.component.html, src/app/core/_components/core-components.module.ts, src/app/core/_components/tables/ht-table/ht-table.component.ts, src/app/core/_components/tables/ht-table/ht-table.models.ts, src/app/core/_components/tables/logs-table/logs-table.component.html, src/app/core/_components/tables/logs-table/logs-table.component.ts, src/app/core/_components/tables/logs-table/logs-table.constants.ts, src/app/core/_datasources/agent-binaries.datasource.ts, src/app/core/_datasources/agents.datasource.ts, src/app/core/_datasources/base.datasource.ts, src/app/core/_datasources/chunks.datasource.ts, src/app/core/_datasources/crackers.datasource.ts, src/app/core/_datasources/files.datasource.ts, src/app/core/_datasources/hashlists.datasource.ts, src/app/core/_datasources/hashtypes.datasource.ts, src/app/core/_datasources/logs.datasource.ts, src/app/core/_datasources/preprocessors.datasource.ts, src/app/core/_datasources/super-hashlists.datasource.ts, src/app/core/_models/log.model.ts
- New logs datasource
- New logs table component
- Implementation of new table component
=> Add logs-table component

src/app/account/account.module.ts, src/app/account/notifications/notification/new-notification.component.html, src/app/account/settings/acc-settings/acc-settings.component.html, src/app/account/settings/ui-settings/ui-settings.component.html, src/app/agents/edit-agent/edit-agent.component.ts, src/app/config/config.module.ts, src/app/config/health-checks/edit-health-check/edit-health-checks.component.html, src/app/config/health-checks/new-health-check/new-health-checks.component.html, src/app/config/health-checks/new-health-check/new-health-checks.component.ts, src/app/core/_components/forms/custom-forms/task/new-supertasks/new-supertasks.component.ts, src/app/core/_constants/healthchecks.config.ts, src/app/core/_constants/select.config.ts, src/app/files/new-files/new-files.component.html, src/app/files/new-files/new-files.component.ts, src/app/hashlists/edit-hashlist/edit-hashlist.component.ts, src/app/hashlists/new-hashlist/new-hashlist.component.html, src/app/hashlists/new-hashlist/new-hashlist.component.ts, src/app/shared/dynamic-form-builder/dynamicform.component.html, src/app/shared/grid-containers/grid-autocol.ts, src/app/shared/utils/forms.ts, src/app/tasks/edit-supertasks/edit-supertasks.component.ts, src/app/tasks/import-supertasks/masks/masks.component.ts, src/app/tasks/import-supertasks/wrbulk/wrbulk.component.ts, src/app/tasks/new-preconfigured-tasks/new-preconfigured-tasks.component.ts, src/app/tasks/new-tasks/new-tasks.component.ts, src/app/tasks/supertasks/applyhashlist.component.ts, src/app/users/edit-users/edit-users.component.html, src/app/users/edit-users/edit-users.component.ts, src/styles/components/_card.scss, src/styles/pages/_files.scss
Summary: In this update, some functions have been refactored and moved to utility functions. Additionally, fixes have been applied to address identified issues. Also Health checks is adapted to Angular Material.
=> Minor changes and Health Check

src/app/core/_components/tables/hashlists-table/hashlists-table.component.ts
Show Hashtype in hashlist overview
=> Hashlist hashtype

src/app/agents/agent-status/agent-status-modal/agent-status-modal.component.html, src/app/agents/agent-status/agent-status-modal/agent-status-modal.component.ts, src/app/agents/agent-status/agent-status.component.html, src/app/agents/agent-status/agent-status.component.ts, src/app/agents/agent.module.ts, src/app/core/_datasources/agents-status.datasource.ts, src/app/core/_pipes/agentstat-color.pipe.ts, src/app/shared/components.module.ts, src/styles/components/_card.scss
Fixing grid and top component. Still missing in the table 2 columns.
=> Agent status part II

src/app/core/_components/menus/base-menu/base-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.component.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.component.ts, src/app/core/_components/tables/tasks-supertasks-table/tasks-supertasks-table.component.html, src/app/core/_components/tables/tasks-supertasks-table/tasks-supertasks-table.component.ts, src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_datasources/tasks-supertasks.datasource.ts, src/app/core/_datasources/tasks.datasource.ts
- Added archive tasks in task overview
- Add bulk actions in modal pretasks
- Modal subtasks in Tasks. Added export options and save columns in local storage
- Modal subtasks in Tasks. Added columns; ID, Name with redirect, Priority with inline edit and Max Agents with inline edit.
- 
Modal subtasks in Tasks. Still missing column Dispatched/Searched, Cracked and Agents, also missing row actions for copy task to pretask/task.
=> Fix archive and modal part II

src/app/core/_components/menus/base-menu/base-menu.component.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.component.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.constants.ts, src/app/core/_components/tables/tasks-supertasks-table/tasks-supertasks-table.component.ts, src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_datasources/tasks-supertasks.datasource.ts, src/app/tasks/edit-tasks/edit-tasks.component.ts
Missing row actions and columns; Dispatch, cracked and Agents. Also fix an error when archiving tasks.
=> Hot fixes iii - Modal subtasks in Tasks

src/app/agents/edit-agent/edit-agent.component.html, src/app/agents/edit-agent/edit-agent.component.ts, src/app/core/_components/core-components.module.ts, src/app/core/_components/menus/base-menu/base-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.constants.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.component.ts, src/app/core/_components/menus/row-action-menu/row-action-menu.constants.ts, src/app/core/_components/tables/agents-status-table/agents-status-table.component.ts, src/app/core/_components/tables/agents-table/agents-table.component.ts, src/app/core/_components/tables/files-table/files-table.component.ts, src/app/core/_components/tables/ht-table/ht-table.models.ts, src/app/core/_components/tables/tasks-chunks-table/tasks-chunks-table.component.html, src/app/core/_components/tables/tasks-chunks-table/tasks-chunks-table.component.ts, src/app/core/_components/tables/tasks-chunks-table/tasks-chunks-table.constants.ts, src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_components/tables/vouchers-table/vouchers-table.component.ts, src/app/core/_components/tables/vouchers-table/vouchers-table.constants.ts, src/app/core/_datasources/files.datasource.ts, src/app/core/_datasources/tasks-chunks.datasource.ts, src/app/core/_datasources/vouchers.datasource.ts, src/app/core/_models/config-ui.model.ts, src/app/shared/graphs/task-visual/task-visual.component.ts, src/app/shared/table/table.component.ts, src/app/tasks/edit-preconfigured-tasks/edit-preconfigured-tasks.component.html, src/app/tasks/edit-tasks/edit-tasks.component.html, src/app/tasks/edit-tasks/edit-tasks.component.ts, src/app/tasks/new-tasks/new-tasks.component.html
It contains chunk tables for agents and tasks, errors when deleting agents, overflown and feedback.
=> Feedback and Chunk tables

src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_datasources/tasks.datasource.ts, src/app/tasks/new-tasks/new-tasks.component.html
- Datasource tasks was not loading, fixed
- New task not showing preprocessor attack on tables when clicking, fixed
=> Hot fix - Tasks not showing and New task preprocessor attack

src/app/core/_services/shared/cookies.service.ts, src/app/hashlists/new-hashlist/new-hashlist.component.ts, src/app/tasks/new-tasks/new-tasks.component.ts
- When creating a hashlist the key to encode was wrong, it was encoding the sourceType instead of the souceData
It was some other errors when initialization the app for first time, when accessing New Haslist or New Task was resulting in an unloaded page or blank page and on refresh error was gone,
- New Hashlist, an issue with a library and some params.
- New Task, issue when building the form with some params.
- Cookies service
=> Patching some initial Errors

src/config/default/app/main.ts
Version was not bumped to 0.14.2
=> Bump version

src/app/core/_components/menus/action-menu/action-menu.component.ts, src/app/core/_components/menus/action-menu/action-menu.model.ts, src/app/core/_components/tables/access-groups-table/access-groups-table.component.ts, src/app/core/_components/tables/access-groups-table/access-groups-table.constants.ts, src/app/core/_components/tables/base-table/base-table.component.ts, src/app/core/_components/tables/health-checks-table/health-checks-table.component.ts, src/app/core/_components/tables/preprocessors-table/preprocessors-table.component.ts, src/app/core/_components/tables/pretasks-table/pretasks-table.component.html, src/app/core/_components/tables/pretasks-table/pretasks-table.component.ts, src/app/core/_components/tables/pretasks-table/pretasks-table.constants.ts, src/app/core/_datasources/access-groups.datasource.ts, src/app/core/_models/access-group.model.ts, src/app/core/_models/config-ui.model.ts, src/app/layout/header/header.component.ts, src/app/tasks/edit-supertasks/edit-supertasks.component.html, src/app/tasks/edit-tasks/edit-tasks.component.html, src/app/tasks/new-preconfigured-tasks/new-preconfigured-tasks.component.ts, src/app/tasks/new-tasks/new-tasks.component.ts
1. On create new Task, error crackerbinaryTypeId=null, Fixed error
2. Edit Task button too much space between them and the first collapse element
3. Edit Task too much space between Assigned Agents and the action dropdown
4. New Pretask red error on submit
5. Edit Supertask, fix text explanation from “Runtime Attack” to Attack Runtime”
6. Edit Supertask change buttons from side to below the form
7. Edit supertask, pretask table handle NaN undefined
8. Pretask table edit inline priority and Max agents should be editable
9. Deleting health check wrong API path
10. Preprocessor hyperlink on click name redirect to edit view
11. Header support hyperlink was not working
12. Header added button to report bug/enhancement
13. Access Groups table missing # of agents and # of users
=> Minor and missing elements

src/app/agents/edit-agent/edit-agent.component.html, src/app/agents/edit-agent/edit-agent.component.ts, src/app/core/_components/tables/chunks-table/chunks-table.component.ts, src/app/core/_components/tables/files-table/files-table.component.ts, src/app/core/_components/tables/hashlists-table/hashlists-table.component.ts, src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_datasources/chunks.datasource.ts, src/app/core/_services/shared/alert.service.ts, src/app/files/new-files/new-files.component.html, src/app/files/new-files/new-files.component.ts, src/app/tasks/new-tasks/new-tasks.component.ts, src/app/tasks/supertasks/applyhashlist.component.html, src/app/tasks/supertasks/applyhashlist.component.ts
Minor changes in style and on delete wrong labels.
=> Week20 - Minor changes

src/app/core/_components/tables/access-groups-table/access-groups-table.component.ts, src/app/core/_components/tables/base-table/base-table.component.ts, src/app/core/_components/tables/crackers-table/crackers-table.component.ts, src/app/core/_components/tables/notifications-table/notifications-table.component.ts, src/app/core/_components/tables/preprocessors-table/preprocessors-table.component.ts, src/app/core/_components/tables/users-table/users-table.component.ts
Fixed a few hyperlinks and on delete some wrong endpoints
=> Hyperlinks and Wrong Delete Endpoints

src/app/core/_components/tables/tasks-table/tasks-table.component.ts
=> The hashlists are now displayed correctly according to the tasks.

.devcontainer/devcontainer.json
Entrypoint support added for Jetbrain IDEs
=> Add: docker entrypoint support for Jetbrain IDEs

package-lock.json, src/app/account/notifications/notification/edit-notification.component.spec.ts, src/app/account/notifications/notification/new-notification.component.html, src/app/account/notifications/notification/new-notification.component.spec.ts, src/app/account/notifications/notification/new-notification.component.ts, src/app/account/settings/acc-settings/acc-settings.component.spec.ts
Some issues with unittests mostly regarding missing imports were fixed.
=> Fixed some issues with unittests

.prettierrc.json, package-lock.json, package.json, src/app/agents/edit-agent/edit-agent.component.html, src/app/agents/edit-agent/edit-agent.component.ts, src/app/core/_constants/select.config.ts, src/app/core/_models/agent-assignment.model.ts, src/app/core/_models/agent.model.ts, src/app/core/_models/base.model.ts, src/app/core/_models/chunk.model.ts, src/app/core/_models/response.model.ts, src/app/core/_models/task.model.ts, src/app/core/_models/user.model.ts, src/app/core/_services/api/serializer-service.ts, src/app/shared/utils/forms.ts
- Add service for Jsona JSON:API serializer/deserializer
- Partially fix Agent Details Page (Chunks still not yet working)
=> Agent details

src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_models/task.model.ts
Use searched and dispatched backend attributes
=> 1220-enhancement-web-ui-use-new-task-attributes-to-display-dispatched-and-searched

src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_datasources/tasks.datasource.ts, src/app/core/_models/task-wrapper.model.ts
made task table more efficient by including the hashlists and hashtypes
=> Make tasks table more efficient

src/app/core/_components/tables/tasks-supertasks-table/tasks-supertasks-table.component.ts
Added Cache to async functions to prevent re-render infinite loop
=> Bugfix tasks-supertasks async functions got called infinitely

src/app/account/account-routing.module.ts, src/app/account/notifications/notification/edit-notification.component.spec.ts, src/app/account/notifications/notification/edit-notification.component.ts, src/app/account/notifications/notification/new-notification.component.spec.ts, src/app/account/notifications/notification/new-notification.component.ts, src/app/account/notifications/notifications.component.ts, src/app/core/_components/tables/notifications-table/notifications-table.component.ts, src/app/core/_datasources/notifications.datasource.ts, src/app/core/_services/main.config.ts
Create new notfification and edit notification now works with new json:api
=> Fix new-notification and edit-notification page

src/app/core/_constants/hashlist.config.ts, src/app/core/_constants/select.config.ts, src/app/core/_services/files/files_tus.service.ts, src/app/hashlists/edit-hashlist/edit-hashlist.component.html, src/app/hashlists/edit-hashlist/edit-hashlist.component.ts, src/app/hashlists/edit-hashlist/edit-hashlist.form.ts, src/app/hashlists/import-cracked-hashes/import-cracked-hashes.component.html, src/app/hashlists/import-cracked-hashes/import-cracked-hashes.component.ts, src/app/hashlists/import-cracked-hashes/import-cracked-hashes.form.ts, src/app/hashlists/new-hashlist/new-hashlist.component.ts, src/app/hashlists/new-hashlist/new-hashlist.form.ts
new-hashlist, edit-hashlist and import-cracked-hashes pages now work with the new json:api
=> Fix new-hashlist, edit-hashlist and import-cracked-hashes

.eslintrc.json, src/app/core/_components/tables/files-attack-table/files-attack-table.component.ts, src/app/core/_components/tables/pretasks-table/pretasks-table.component.ts, src/app/core/_datasources/preconfigured-tasks.datasource.ts, src/app/tasks/new-preconfigured-tasks/new-preconfigured-tasks.component.ts, src/app/tasks/new-preconfigured-tasks/new-preconfigured-tasks.form.ts, src/app/tasks/preconfigured-tasks/preconfigured-tasks.component.ts
- Deactivate ESLint rule "prefer-standalone"
- Fix preconfigured tasks table infinite loading spinner, if table empty
- Make new-preconfigured tasks work with json:api
=> Fix pretasks

src/app/shared/input/select/select.component.html, src/app/shared/input/select/select.component.ts, src/app/users/all-users/all-users.component.ts, src/app/users/new-user/new-user.component.html, src/app/users/new-user/new-user.component.spec.ts, src/app/users/new-user/new-user.component.ts, src/app/users/new-user/new-user.form.ts, src/app/users/users-routing.module.ts, src/app/users/users.module.ts
- Replaced generic FormComponent with newly created NewUserComponent handling creation of new users as  FormComponent did not load globalPermissionGroups from server and seemed to complicated to adapt.
- Modify select component to show loading status inside
=> Fix new user page not loading globalPermissionGroups

src/app/core/_components/tables/cracks-table/cracks-table.component.ts, src/app/core/_datasources/cracks.datasource.ts, src/app/hashlists/show-cracks/show-cracks.component.ts
Show cracks table now shows taskName instead of taskID in table
=> Show cracks table now shows taskName instead of taskID in table

src/app/agents/agent.module.ts, src/app/agents/agents-routing.module.ts, src/app/agents/edit-agent/edit-agent.component.ts, src/app/agents/edit-agent/edit-agent.form.ts, src/app/core/_components/tables/agents-table/agents-table.component.ts, src/app/core/_components/tables/base-table/base-table.component.ts
Fixed bug leading to tasks not being unassignable in the edit-task-page
=> Fix bug updating assignments in edit-agent

Dockerfile
Docker build complains if keyword cases (FROM, as) are not consistent.
=> Fix keyword case inconsistency

src/app/core/_components/tables/access-groups-table/access-groups-table.component.ts, src/app/core/_components/tables/agent-binaries-table/agent-binaries-table.component.ts, src/app/core/_components/tables/agents-status-table/agents-status-table.component.ts, src/app/core/_components/tables/agents-table/agents-table.component.ts, src/app/core/_components/tables/crackers-table/crackers-table.component.ts, src/app/core/_components/tables/files-table/files-table.component.ts, src/app/core/_components/tables/hashlists-table/hashlists-table.component.ts, src/app/core/_components/tables/hashtypes-table/hashtypes-table.component.ts, src/app/core/_components/tables/health-checks-table/health-checks-table.component.ts, src/app/core/_components/tables/notifications-table/notifications-table.component.ts, src/app/core/_components/tables/permissions-table/permissions-table.component.ts, src/app/core/_components/tables/preprocessors-table/preprocessors-table.component.ts, src/app/core/_components/tables/pretasks-table/pretasks-table.component.ts, src/app/core/_components/tables/super-hashlists-table/super-hashlists-table.component.ts, src/app/core/_components/tables/supertasks-pretasks-table/supertasks-pretasks-table.component.ts, src/app/core/_components/tables/supertasks-table/supertasks-table.component.ts, src/app/core/_components/tables/tasks-table/tasks-table.component.ts, src/app/core/_components/tables/users-table/users-table.component.ts, src/app/core/_components/tables/vouchers-table/vouchers-table.component.ts, src/app/core/_services/api/serializer-service.ts, src/app/core/_services/main.service.ts, src/app/tasks/edit-supertasks/edit-supertasks.component.html, src/app/tasks/edit-supertasks/edit-supertasks.component.ts
Added the new way of bulk actions to the frontend. This pull request is reliant on pull request #1330
=> Bulk actions

src/app/core/_components/tables/agents-status-table/agents-status-table.component.ts, src/app/core/_components/tables/agents-table/agents-table.component.ts, src/app/core/_components/tables/files-table/files-table.component.ts, src/app/shared/utils/util.ts
=> 1283-enhancement-add-number-separator-for-all-relevant-numbers

src/app/core/_components/tables/search-hash-table/search-hash-table.component.ts, src/app/core/_components/tables/search-hash-table/search-hash-table.constants.ts, src/app/core/_datasources/search-hash.datasource.ts, src/app/core/_models/config-ui.model.ts
- search for multiple hashes
- show plaintext for cracked hashes
- code refactored
=> 1244-bug-search-hashes

src/app/core/_components/tables/health-check-agents-table/health-check-agents-table.component.ts, src/app/core/_components/tables/health-check-agents-table/health-check-agents-table.constants.ts, src/app/core/_components/tables/ht-table/ht-table.component.ts, src/app/core/_models/config-ui.model.ts
- Remove cracked column from healtchecks #1300
- Check localstorage for invalid column ID #1312
=> Fix: check for removed column when setting values from local storage

src/app/shared/input/multiselect/multiselect.component.ts
1290 bug searching hashtypes in hashlists leads to display bug
=> Fix bug deleting search text in hashlist multiselect component

src/app/core/_components/menus/row-action-menu/row-action-menu.component.ts, src/app/core/_components/tables/agents-table/agents-table.component.ts
* Workflow
1. if agent is assigned to a task -> row action unassign -> agent is now unassigned from the task
2. If agent is not assigned to a task -> row action delete agent -> agent is now deleted
=> 1310 bug change name and functionality of action delete agent

src/app/core/_datasources/hashes.datasource.ts, src/app/core/_models/config-ui.model.ts, src/app/hashlists/hashes/hashes.component.html, src/app/hashlists/hashes/hashes.component.ts
=> - Performance optimization

src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.component.ts, src/app/core/_components/menus/bulk-action-menu/bulk-action-menu.constants.ts, src/app/core/_components/tables/access-groups-agents-table/access-groups-agents-table.component.html, src/app/core/_components/tables/access-groups-agents-table/access-groups-agents-table.component.ts, src/app/core/_components/tables/access-groups-users-table/access-groups-users-table.component.html, src/app/core/_components/tables/access-groups-users-table/access-groups-users-table.component.ts, src/app/core/_constants/select.config.ts, src/app/core/_services/main.config.ts, src/app/core/_services/main.service.ts, src/app/users/edit-groups/edit-groups.component.html, src/app/users/edit-groups/edit-groups.component.ts, src/app/users/edit-groups/edit-groups.form.ts
Updated edit access group page:
- Add users and agents to access group via multiselect
- Remove users and agents from access group via bulk action in userMember and agentMember tables
=> 1226 bug access group management

src/app/core/_interceptors/auth-interceptor.service.ts, src/app/core/_interceptors/http-res.interceptor.ts, src/app/core/_services/access/auth.service.ts
* The user is now logged out when the token expires
* refesh token is for the future
=> 1205 enhancement webui better handling of expired jwt token

src/app/core/_components/tables/ht-table/ht-table.component.html
* Pagination should not be clicked when new data is loading
=> disable while loading

src/app/core/_models/file.model.ts, src/app/tasks/new-tasks/new-tasks.component.spec.ts, src/app/tasks/new-tasks/new-tasks.component.ts
* copy task works
* fixed recursive call 
* added test
=> 1495 bug error while to try to copy a task into another task

src/app/tasks/new-preconfigured-tasks/new-preconfigured-tasks.component.ts, src/app/tasks/new-tasks/new-tasks.component.ts
* fixed id for pre / task
* fixed any type
=> 1499 bug error while to try to copy a pretask into a pretask

src/app/files/new-files/new-files.component.html, src/app/files/new-files/new-files.component.ts, src/app/files/new-files/new-files.form.ts
#1534 should be merged first to make this work
=> frontend changes to make it possible to upload files with url

.github/workflows/audit.yml
=> Ci npm audit
